# User config for makepkg. See `man makepkg.conf` for more details.
# Global config is in /etc/makepkg.conf. These here are overwrites of the global config.

# Disable debug symbols, as they tend to conflict with one another. 
# Other options (other than debug) are left as default, so if other options differ from the global config, change them to match the global config.
OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)
